### ISSUE TITLE
Links precisam de diferenciação na página

### ISSUE THREAD

**Issue by naoliv** [OSMBrasil/OSMBrasil.github.io#12]
Precisa alterar o estilo dos links da página.
Por exemplo, visualmente não dá para saber que os locais apontados são links:

![nao-fs8](https://cloud.githubusercontent.com/assets/982338/3960553/8bd4b608-2742-11e4-9bc0-148918493f8c.png)

Só ficam diferentes após visitá-los.

**Comment by jgpacker** [comment]
Agora os links estão com uma cor de azul claro, e estão bem mais evidentes. Não sei dizer se é a melhor cor ou não, mas creio que o problema relatado aqui foi resolvido.

**Comment by alexandre-mbm** [comment]
Eu não tinha apertado o botão de fechar issue para você porque ainda acho estranho o itálico nos links. Mas não há problemas, isso poderá ser implicitamente resolvido (sem issue) no milestone [Design](milestones/Design).
