### ISSUE TITLE
Página /dados não possui conteúdo

### ISSUE THREAD

**Issue by jgpacker** [OSMBrasil/OSMBrasil.github.io#15]
Já faz um bom tempo que esta página se encontra vazia.
Eu acredito que se ninguém estiver disposto a adicionar conteúdo nela, então deveríamos remover esta do site.

Alguém planeja adicionar conteúdo nesta página?

**Comment by alexandre-mbm** [comment]
Eu não pretendo. Mas penso ser válida a proposta da página. Minha sugestão é que apenas o link, lá no cabeçalho do site, seja desativado, continuando a existir a página propriamente dita.

**Comment by jgpacker** [comment]
@alexandre-mbm O link do cabeçalho era feito dinamicamente, logo exclui o arquivo mesmo.

Removi a página "Dados" em a7c8c958144db24a8f417e747578fc2e3d95dd6a.
A idéia de removê-la é porque uma página vazia como esta dá um aspecto de abandonado para o site.

Se alguém quiser trabalhar nesta página que foi removida, pode fazer isto executamente o comando abaixo, que recuperava a exclusão que acabei de fazer.

    git revert a7c8
