### ISSUE TITLE
Backup ou proteção contra git -f push

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/OSMBrasil.github.io#16]
Seguem os resultados de uma pesquisa no Google.

Podemos estudar o uso de _hooks_:
- [stefansundin / install-pre-push.sh](https://gist.github.com/stefansundin/d465f1e331fc5c632088)
- [Do not allow force push to master](http://blog.bigbinary.com/2013/09/19/do-not-allow-force-pusht-to-master.html) ‒ BIGbinary
  - **[tiny_scripts/git-hooks/hooks/pre-push](https://github.com/bigbinary/tiny_scripts/blob/master/git-hooks/hooks/pre-push)** ‒ Ruby
- [Git: Disable Force Push](https://coderwall.com/p/wo3kng/git-disable-force-push)
  - `git config --system receive.denyNonFastForwards true`
  - [pixelhandler / pre-push.sh](https://gist.github.com/pixelhandler/5718585)
- [GIT Hack: Prevent pushing to master](http://dev.ghost.org/prevent-master-push/)
  - **Oops!** _"Many projects use GitHub as their remote repository, and as GitHub is a service, they do not permit you to upload arbitrary scripts to run on their servers."_

---

Se fosse GitHub Enterprise...
- Blocking force pushes to a repository
  - [11.10.340](https://help.github.com/enterprise/11.10.340/admin/articles/blocking-force-pushes-to-a-repository/)
  - [2.1](https://help.github.com/enterprise/2.1/admin/articles/blocking-force-pushes-to-a-repository/)
  - [2.2](https://help.github.com/enterprise/2.2/admin/articles/blocking-force-pushes-to-a-repository/)

Mas como não é:
- **[Elegant solution to prevent force push on master only](http://stackoverflow.com/a/24436947/3391915)**
- [GitHub - prevent collaborators from using push -f](http://stackoverflow.com/a/5094762/3391915)

E se fosse GitLab...
- [Keeping your code protected](https://about.gitlab.com/2014/11/26/keeping-your-code-protected/)

---

@naoliv já configurou [BackHub](https://backhub.co/). Uma ideia seria, para além disso, ter um _hook_ fazendo backup em branch automaticamente nomeado e empurrado para o GitHub. Ou ao menos avisando dos perigos. ~~Que eu saiba, os _hooks_ são compartilhados com todas as pessoas que fazem _pull_ do código.~~ — _errado_

**Comment by naoliv** [comment]
Eu comecei a fazer backup de tudo em http://backhub.co/

**Comment by alexandre-mbm** [comment]
Pelo que entendi, ele é de uso pessoal, sem interface pública. A imagem a seguir dá a entender que os backups "ativos" são realizados automaticamente:
![backhub-recurring](https://cloud.githubusercontent.com/assets/957501/7900144/a789d08a-071c-11e5-8f82-4447d9f17bf8.png)
Você testou se ele rastreia o `push -f` ou perda de HEAD?

**Comment by naoliv** [comment]
Então, ele restaura tudo pra um determinado momento que foi feito backup (como se fossem vários spanshots).
Recuperaria qualquer coisa que aconteceu.

**Comment by alexandre-mbm** [comment]
Por enquanto, ter o seu BackHub com todos esses backups é suficiente. Quando tivermos tempo e interesse, podemos avaliar, a partir daqueles 5 links (acima), o uso de um _hook_ `pre-push`.

**Comment by jgpacker** [comment]
Magno, obrigado por ajudar a recuperar os commits que perdi acidentalmente. :-)

Felizmente parece que o único commit que não foi recuperado foi um commit meu onde arrumei um link, mas posso corrigi-lo novamente sem problema.

**Comment by alexandre-mbm** [comment]
Acho que lembro-me desse commit, e acho que lembro-me de realmente não ter feito pull com ele.

**Comment by naoliv** [comment]
Fui verificar agora e o https://backhub.co/ não serve
Só armazena uma cópia (então se fizer backup bem depois de perder algo, não tem utilidade)

**Comment by alexandre-mbm** [comment]
Então penso que devemos aprender e desenvolver _hooks_, para soluções de contorno.

**Comment by Skippern** [comment]
Um solução pode ser algum clonando o repo pelo computador próprio e fazendo backups diaramente/semanalmente

pode ser um tarefa cron

**Comment by alexandre-mbm** [comment]
Outra é aquela do _hook_, recomendado como "boa prática" a todos com poderes de escrita, detectar o `-f push` (forçado) e empurrar _branch_ de backup antecedendo-o.

**Comment by alexandre-mbm** [comment]
**Nenhuma solução com _hook_ nos servirá.** Do [lado do servidor](http://stackoverflow.com/a/9832377): GitHub não aceita. Do lado do cliente: [exigiria](http://stackoverflow.com/a/12222225) uma cultura generalizada de instalar o _hook_ localmente. Um [`pre-push`](http://blog.bigbinary.com/2013/09/19/do-not-allow-force-pusht-to-master.html) [[1]](https://gist.github.com/pixelhandler/5718585) [[2]](https://gist.github.com/stefansundin/d465f1e331fc5c632088), por exemplo.

Duas [sugestões](https://coderwall.com/p/wo3kng/git-disable-force-push) de solução de contorno para quem usa GitHub (como nós) são:

1. Limitar o grupo de pessoas que tem poder para `push`, requerendo _pull requests_ a todos os demais;
1. ~~Ter um repositório remoto intermediário com um _hook_ `pre-receive`~~ — _inviável_

Agora, dizem que o GitHub [**pode**](http://stackoverflow.com/a/30703256) fazer uma configuração pra nós...

**Comment by alexandre-mbm** [comment]
[Parece](https://help.github.com/articles/about-protected-branches/) que o GitHub está com recurso novo:

![github-branch-protection](https://cloud.githubusercontent.com/assets/957501/10092656/54174ebe-631f-11e5-8fd3-c3bc143ab320.png)
