### ISSUE TITLE
Necessidade de novo serviço de webchat pro IRC

### ISSUE THREAD

**Issue by naoliv** [OSMBrasil/OSMBrasil.github.io#29]
O scrollback não anda confiável (está caindo toda hora e muitas vezes, apesar de estar online, não mostra as conversas trocadas na sala).
Várias vezes já deu para perceber pessoas falando sozinhas no scrollback e nada era enviado ao canal.

Precisa ver um outro endereço para colocar na página ou então voltar a utilizar o anterior http://webchat.oftc.net/?channels=osm-br

**Comment by alexandre-mbm** [comment]
O Slack tem uma funcionalidade web muito interessante. Também tem gateway IRC e XMPP, com uma série de ferramentas. Dentre elas, [slack-irc] e [slack-irc-plugin].

[slack-irc]: https://github.com/ekmartin/slack-irc
[slack-irc-plugin]: https://github.com/jimmyhillis/slack-irc-plugin

**Comment by naoliv** [comment]
Basicamente tudo acontece no Telegram agora.
Não vejo mais necessidade de IRC para o público em geral.
