### ISSUE TITLE
Migração para domínio .org.br

### ISSUE THREAD

**Issue by vgeorge** [OSMBrasil/OSMBrasil.github.io#34]
Dei início à migração deste website para o domínio www.openstreetmap.org.br. 

Fiz a alteração do CNAME e coloquei os campos DNS, seguindo instruções do Github: 

<img width="543" alt="Screenshot 2020-05-02 11 34 50" src="https://user-images.githubusercontent.com/329694/80861936-758f4600-8c69-11ea-9caf-6181971f9895.png">

No momento deve estar havendo a propagação. Se tudo estiver certo, até o final do dia o site aparecer no novo endereço.

Após a conclusão desta etapa, teremos que:

- Configurar o redirecionamento do domínio www.openstreetmap.com.br para org.br (Thierry)
- Habilitar HTTPS

**Comment by vgeorge** [comment]
Atualização, o site está no ar em www.openstreetmap.org.br. Habilitei SSL, mas deve demorar algum tempo para entrar.

**Comment by eduaddad** [comment]
@vgeorge também poderia adicionar o favicon para aparecer no site

**Comment by vgeorge** [comment]
@eduaddad esta issue é para tratar do domínio, poderia abrir uma nova issue para tratar do favicon?

**Comment by eduardoaddad** [comment]
Vou fazer isso

Em ter, 19 de mai de 2020 11:30, Vitor George <notifications@github.com>
escreveu:

**Comment by vgeorge** [comment]
A migração de domínio está completa.
