### ISSUE TITLE
Chamada da página inicial

### ISSUE THREAD

**Issue by alexandre-mbm** [OSMBrasil/OSMBrasil.github.io#9]
Invés de:

**`Conheça o OpenStreetMap, o mapa livre do mundo`**
`O OpenStreetMap é um projeto de produção colaborativa de dados geo-espaciais abertos.
Qualquer pessoa pode editar o mapa e os dados são redistribuídos sob uma licença aberta.`

Apenas:

**`O mundo mapeado com dados livres`**
`Um projeto de produção colaborativa de dados geo-espaciais abertos e reutilizáveis.
Qualquer pessoa pode editar o mapa e os dados são `[`redistribuídos sob a licença ODbl`](http://www.openstreetmap.org/copyright)`.`

**Comment by alexandre-mbm** [comment]
```diff
- Conheça o OpenStreetMap, o mapa livre do mundo 
+ Conheça o OpenStreetMap, o mundo em um mapa livre
```
```diff
- Qualquer pessoa pode editar o mapa e os dados são redistribuídos sob uma licença aberta. 
+ Qualquer pessoa pode editar o mapa. O dados são redistribuídos sob uma licença aberta. 
```

 @OSMBrasil/owners,  que acham disso?

**Comment by jgpacker** [comment]
Acho que "o mapa livre do mundo" fica melhor.
A segunda parte pode ser como você sugeriu.

**Comment by alexandre-mbm** [comment]
> Acho que "o mapa livre do mundo" fica melhor.

Fico com sensação de "o mapa _**que é**_ livre do mundo".

**Comment by alexandre-mbm** [comment]
Discussão migrou para #24.
